# Generated by Django 5.1.2 on 2025-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel1', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='no_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
